In [2]:
pip install mysql-connector-python

Collecting mysql-connector-python
  Using cached mysql_connector_python-9.2.0-cp312-cp312-win_amd64.whl.metadata (6.2 kB)
Using cached mysql_connector_python-9.2.0-cp312-cp312-win_amd64.whl (16.1 MB)
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.2.0
Note: you may need to restart the kernel to use updated packages.

# hacer importaciones necesarias

In [3]:
import pandas as pd
import mysql.connector
import random

# leer archivo

In [4]:
# Leer archivo Excel
df = pd.read_excel(r"D:\prueba_tecnica_deloite\Escaneo_Prueba.xlsx")

In [5]:
df.head()

,IP,First Detected,Last Detected,CVE ID,Gid,Categoria,Riesgo,Criticidad
0,192168100101,11/30/2022 11:13:23,44816.76875,CVE-2022-4135,1,Actualizacion navegadores,Alto,Transaccional
1,192168100101,44876.917361,44816.76875,"CVE-2022-3887, CVE-2022-3885, CVE-2022-3888, C...",1,Actualizacion navegadores,Bajo,General
2,192168100101,44754.55,44816.76875,"CVE-2022-4262, CVE-2022-44708, CVE-2022-4195, ...",1,Actualizacion navegadores,Alto,General
3,192168100101,07/21/2022 09:54:29,44816.76875,"CVE-2022-34169, CVE-2022-21541, CVE-2022-21540...",2,Actualizacion java,Medio,General
4,192168100101,07/16/2022 21:19:12,07/28/2022 10:24:01,"CVE-2022-34219, CVE-2022-34232, CVE-2022-34229...",3,Actualizacion software,Bajo,General

# Simular datos requeridos como en la base de datos no tiene  impacto, probabilidad, ni riesgo

In [6]:
# Simular datos requeridos
#CVE ID (Common Vulnerabilities and Exposures)
# contiene el identificador único de vulnerabilidades reales
df['nombre'] = df['CVE ID'].astype(str).str.slice(0, 255)
df['impacto'] = [random.randint(1, 10) for _ in range(len(df))] 
# creamos aleatoriamente impactos y probabilidades
df['probabilidad'] = [random.randint(1, 10) for _ in range(len(df))]
df['riesgo'] = df['impacto'] * df['probabilidad'] #impacto * probabilidad

In [7]:
df.head()

,IP,First Detected,Last Detected,CVE ID,Gid,Categoria,Riesgo,Criticidad,nombre,impacto,probabilidad,riesgo
0,192168100101,11/30/2022 11:13:23,44816.76875,CVE-2022-4135,1,Actualizacion navegadores,Alto,Transaccional,CVE-2022-4135,10,7,70
1,192168100101,44876.917361,44816.76875,"CVE-2022-3887, CVE-2022-3885, CVE-2022-3888, C...",1,Actualizacion navegadores,Bajo,General,"CVE-2022-3887, CVE-2022-3885, CVE-2022-3888, C...",1,1,1
2,192168100101,44754.55,44816.76875,"CVE-2022-4262, CVE-2022-44708, CVE-2022-4195, ...",1,Actualizacion navegadores,Alto,General,"CVE-2022-4262, CVE-2022-44708, CVE-2022-4195, ...",1,5,5
3,192168100101,07/21/2022 09:54:29,44816.76875,"CVE-2022-34169, CVE-2022-21541, CVE-2022-21540...",2,Actualizacion java,Medio,General,"CVE-2022-34169, CVE-2022-21541, CVE-2022-21540...",8,10,80
4,192168100101,07/16/2022 21:19:12,07/28/2022 10:24:01,"CVE-2022-34219, CVE-2022-34232, CVE-2022-34229...",3,Actualizacion software,Bajo,General,"CVE-2022-34219, CVE-2022-34232, CVE-2022-34229...",8,2,16

# Conectar a MySQL con los datos y hacer consulta mysql

In [ ]:
#conecta mysql con los datos
db_connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="password",
    database="ciberseguridad"
)
cursor = db_connection.cursor()

# Crear tabla si no existe
cursor.execute("""
CREATE TABLE IF NOT EXISTS riesgos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    impacto INT NOT NULL,
    probabilidad INT NOT NULL,
    riesgo FLOAT NOT NULL
)
""")

# Insertar datos
insert_query = """
INSERT INTO riesgos (nombre, impacto, probabilidad, riesgo)
VALUES (%s, %s, %s, %s)
"""

for _, row in df.iterrows():
    cursor.execute(insert_query, (
        row['nombre'], row['impacto'], row['probabilidad'], row['riesgo']
    ))

db_connection.commit()

# Consultar riesgos > 50
cursor.execute("SELECT * FROM riesgos WHERE riesgo > 50")
resultados = cursor.fetchall()

# Mostrar resultados
for fila in resultados:
    print(fila)

# Cerrar conexión
cursor.close()
db_connection.close()

(5, 'CVE-2022-4135', 10, 7, 70.0)
(8, 'CVE-2022-34169, CVE-2022-21541, CVE-2022-21540, CVE-2022-21549', 8, 10, 80.0)
(19, 'CVE-2022-37963, CVE-2022-37962, CVE-2022-38010', 8, 10, 80.0)
(21, 'CVE-2022-41045, CVE-2022-41039, CVE-2022-41109, CVE-2022-41100, CVE-2022-41099, CVE-2022-41098, CVE-2022-41097, CVE-2022-41095, CVE-2022-41096, CVE-2022-41093, CVE-2022-41092, CVE-2022-41090, CVE-2022-41088, CVE-2022-41086, CVE-2022-41058, CVE-2022-41057,', 8, 10, 80.0)
(35, 'CVE-2022-22709, CVE-2022-21927, CVE-2022-21926, CVE-2022-21844', 9, 8, 72.0)
(42, 'CVE-2021-31984', 9, 9, 81.0)
(45, 'CVE-2021-28465', 9, 8, 72.0)
(46, 'CVE-2021-28466, CVE-2021-28464, CVE-2021-28468', 8, 9, 72.0)
(55, 'CVE-2020-14803', 9, 8, 72.0)
(63, 'CVE-2022-26832', 10, 10, 100.0)
(83, 'CVE-2025-1414', 10, 8, 80.0)
(85, 'CVE-2025-1016, CVE-2025-1019, CVE-2025-1013, CVE-2025-1010, CVE-2025-1017, CVE-2025-1020, CVE-2025-1011, CVE-2025-1018, CVE-2025-1012, CVE-2025-1014, CVE-2025-1009', 9, 8, 72.0)
(86, 'CVE-2025-0762', 8, 9, 72.0)
(96, 'CVE-2024-10467, CVE-2024-10461, CVE-2024-10468, CVE-2024-10466, CVE-2024-10463, CVE-2024-10459, CVE-2024-10465, CVE-2024-10460, CVE-2024-10462, CVE-2024-10458, CVE-2024-10464', 10, 6, 60.0)
(103, 'CVE-2023-41993, CVE-2024-21085, CVE-2024-21011, CVE-2024-21068, CVE-2024-21094, CVE-2024-21012, CVE-2024-21003, CVE-2024-21005, CVE-2024-21002, CVE-2024-21004', 8, 9, 72.0)
(110, 'CVE-2023-21835, CVE-2023-21830, CVE-2023-21843', 7, 9, 63.0)
(118, 'CVE-2025-21262', 9, 8, 72.0)
(121, 'CVE-2023-35080, CVE-2023-38543, CVE-2023-38043, CVE-2023-41718', 6, 10, 60.0)
(125, 'CVE-2023-40036, CVE-2023-40164, CVE-2023-40166, CVE-2023-40031', 8, 9, 72.0)
(139, 'CVE-2025-21307', 8, 9, 72.0)
(141, 'CVE-2024-43629, CVE-2024-43451, CVE-2024-43644, CVE-2024-43630, CVE-2024-43626, CVE-2024-49039, CVE-2024-38203, CVE-2024-43642, CVE-2024-43641, CVE-2024-43640, CVE-2024-43636, CVE-2024-43635, CVE-2024-43633, CVE-2024-43624, CVE-2024-43622, CVE-2024-43621,', 9, 6, 54.0)
(142, 'CVE-2024-43582, CVE-2024-43570, CVE-2024-43562, CVE-2024-43558, CVE-2024-43553, CVE-2024-43536, CVE-2024-43520, CVE-2024-43511, CVE-2024-37983, CVE-2024-43573, CVE-2024-43540, CVE-2024-43534, CVE-2024-43526, CVE-2024-43518, CVE-2024-43506, CVE-2024-43583,', 8, 8, 64.0)
(144, 'CVE-2024-38155, CVE-2024-38152, CVE-2024-38146, CVE-2024-38143, CVE-2024-38140, CVE-2024-38134, CVE-2024-38127, CVE-2024-38122, CVE-2024-38117, CVE-2024-38114, CVE-2024-38106, CVE-2024-38193, CVE-2024-38178, CVE-2024-38223, CVE-2024-38215, CVE-2024-38214,', 9, 6, 54.0)
(148, 'CVE-2025-0762', 10, 7, 70.0)
(151, 'CVE-2025-0411', 7, 10, 70.0)
(154, 'CVE-2024-49530, CVE-2024-49531, CVE-2024-49532, CVE-2024-49533, CVE-2024-49534, CVE-2024-49535', 8, 8, 64.0)
(159, 'CVE-2024-41869, CVE-2024-45112', 7, 10, 70.0)
(160, 'CVE-2024-39383, CVE-2024-39422, CVE-2024-39423, CVE-2024-39424, CVE-2024-39425, CVE-2024-39426, CVE-2024-41830, CVE-2024-41831, CVE-2024-41832, CVE-2024-41833, CVE-2024-41834, CVE-2024-41835, CVE-2024-39420, CVE-2024-45107', 9, 9, 81.0)
(161, 'CVE-2024-21147, CVE-2024-21145, CVE-2024-21140, CVE-2024-21144, CVE-2024-21131, CVE-2024-21138', 10, 7, 70.0)
(163, 'CVE-2023-38042', 6, 10, 60.0)
(167, 'CVE-2024-49026, CVE-2024-49027, CVE-2024-49028, CVE-2024-49029, CVE-2024-49030, CVE-2024-49031, CVE-2024-49032, CVE-2024-49033', 10, 7, 70.0)
(176, 'CVE-2024-30099, CVE-2024-30097, CVE-2024-30096, CVE-2024-35265, CVE-2024-30095, CVE-2024-30094, CVE-2024-30093, CVE-2024-30091, CVE-2024-30090, CVE-2024-30089, CVE-2024-30088, CVE-2024-30087, CVE-2024-30086, CVE-2024-30085, CVE-2024-30084, CVE-2024-30083,', 7, 8, 56.0)
(179, 'CVE-2023-38170', 10, 8, 80.0)
(181, 'CVE-2023-29340, CVE-2023-29341', 7, 9, 63.0)
(184, 'CVE-2022-30168', 9, 6, 54.0)
(186, 'CVE-2022-23300, CVE-2022-22007, CVE-2022-23301, CVE-2022-24451, CVE-2022-24452, CVE-2022-24453, CVE-2022-24457, CVE-2022-23295, CVE-2022-22006, CVE-2022-24501, CVE-2022-24456', 7, 9, 63.0)
(187, 'CVE-2022-22709, CVE-2022-21927, CVE-2022-21926, CVE-2022-21844', 7, 9, 63.0)
(199, 'CVE-2021-1643, CVE-2021-1644', 7, 10, 70.0)
(202, 'CVE-2025-23040', 7, 10, 70.0)
(204, 'CVE-2024-8539, CVE-2024-38654, CVE-2024-9842, CVE-2024-9843, CVE-2024-29211, CVE-2024-37398, CVE-2024-7571', 8, 9, 72.0)
(223, 'nan', 7, 8, 56.0)
(224, 'nan', 10, 6, 60.0)
(232, 'CVE-2023-29299, CVE-2023-29303, CVE-2023-29320, CVE-2023-38222, CVE-2023-38223, CVE-2023-38224, CVE-2023-38225, CVE-2023-38226, CVE-2023-38227, CVE-2023-38228, CVE-2023-38229, CVE-2023-38230, CVE-2023-38231, CVE-2023-38232, CVE-2023-38233, CVE-2023-38234,', 7, 9, 63.0)
(234, 'CVE-2024-21384, CVE-2024-20673, CVE-2024-21379, CVE-2024-21413', 8, 7, 56.0)
(238, 'CVE-2025-21217, CVE-2025-21246, CVE-2025-21334, CVE-2025-21374, CVE-2025-21343, CVE-2025-21340, CVE-2025-21312, CVE-2025-21300, CVE-2025-21292, CVE-2025-21276, CVE-2025-21189, CVE-2025-21261, CVE-2025-21278, CVE-2025-21229, CVE-2025-21228, CVE-2025-21331,', 9, 10, 90.0)
(254, 'CVE-2023-21729, CVE-2023-28302, CVE-2023-28298, CVE-2023-28297, CVE-2023-28293, CVE-2023-28253, CVE-2023-28275, CVE-2023-28276, CVE-2023-28252, CVE-2023-28274, CVE-2023-28273, CVE-2023-28249, CVE-2023-28272, CVE-2023-28271, CVE-2023-28247, CVE-2023-28248,', 10, 7, 70.0)
(255, 'CVE-2025-1006, CVE-2025-1426, CVE-2025-0999', 9, 8, 72.0)
(267, 'CVE-2024-12695, CVE-2024-12694, CVE-2024-12693, CVE-2024-12692', 9, 6, 54.0)
(269, 'CVE-2024-11477', 9, 9, 81.0)
(270, 'CVE-2024-11395', 7, 8, 56.0)
(274, 'CVE-2024-10826, CVE-2024-10827', 8, 8, 64.0)
(277, 'CVE-2024-9954, CVE-2024-9955, CVE-2024-9956, CVE-2024-9957, CVE-2024-9958, CVE-2024-9959, CVE-2024-9960, CVE-2024-9961, CVE-2024-9962, CVE-2024-9963, CVE-2024-9964, CVE-2024-9965, CVE-2024-9966', 9, 10, 90.0)
(289, 'CVE-2024-7532, CVE-2024-7533, CVE-2024-7550, CVE-2024-7534, CVE-2024-7535, CVE-2024-7536', 10, 8, 80.0)
(290, 'CVE-2024-6990, CVE-2024-7255, CVE-2024-7256', 7, 10, 70.0)
(298, 'CVE-2024-5274', 9, 10, 90.0)
(305, 'CVE-2024-4558, CVE-2024-4559', 9, 6, 54.0)
(318, 'CVE-2024-1284, CVE-2024-1283', 9, 8, 72.0)
(319, 'CVE-2024-1077, CVE-2024-1059, CVE-2024-1060, CVE-2024-21399', 9, 9, 81.0)
(324, 'CVE-2024-0208', 9, 10, 90.0)
(325, 'CVE-2024-0222, CVE-2024-0223, CVE-2024-0224, CVE-2024-0225', 7, 8, 56.0)
(329, 'CVE-2023-6351, CVE-2023-6350, CVE-2023-6348, CVE-2023-6347, CVE-2023-6346, CVE-2023-6345', 10, 9, 90.0)
(331, 'nan', 6, 10, 60.0)
(339, 'CVE-2023-5487, CVE-2023-5484, CVE-2023-5481, CVE-2023-5479, CVE-2023-5476, CVE-2023-5218, CVE-2023-5474, CVE-2023-5478, CVE-2023-5477, CVE-2023-5473, CVE-2023-5485, CVE-2023-5486, CVE-2023-5475, CVE-2023-5483', 8, 9, 72.0)
(343, 'CVE-2023-26369', 10, 6, 60.0)
(353, 'CVE-2023-3422, CVE-2023-3421, CVE-2023-3420', 9, 8, 72.0)
(356, 'CVE-2023-2722, CVE-2023-2724, CVE-2023-2723, CVE-2023-2721, CVE-2023-2725, CVE-2023-2726', 8, 7, 56.0)
(364, 'CVE-2023-0699, CVE-2023-0698, CVE-2023-0700, CVE-2023-0701, CVE-2023-0697, CVE-2023-0696, CVE-2023-21794, CVE-2023-0703, CVE-2023-0705, CVE-2023-0702, CVE-2023-0704', 9, 7, 63.0)
(365, 'CVE-2023-0705, CVE-2023-0703, CVE-2023-0702, CVE-2023-0701, CVE-2023-0704, CVE-2023-0697, CVE-2023-0700, CVE-2023-0698, CVE-2023-0699, CVE-2023-0696', 9, 7, 63.0)
(369, 'CVE-2022-21628, CVE-2022-21626, CVE-2022-21618, CVE-2022-39399, CVE-2022-21624, CVE-2022-21619', 9, 9, 81.0)
(372, 'CVE-2025-21395, CVE-2025-21366, CVE-2025-21365, CVE-2025-21338, CVE-2025-21364, CVE-2025-21363, CVE-2025-21362, CVE-2025-21402, CVE-2025-21356, CVE-2025-21354, CVE-2025-21186, CVE-2025-21346, CVE-2025-21345', 10, 7, 70.0)
(375, 'CVE-2024-43616, CVE-2024-43609, CVE-2024-43576, CVE-2024-43505, CVE-2024-43504', 9, 6, 54.0)
(376, 'CVE-2024-38016, CVE-2024-38226, CVE-2024-43465, CVE-2024-43463, CVE-2024-38250', 6, 10, 60.0)
(377, 'CVE-2024-38189, CVE-2024-38171, CVE-2024-38170, CVE-2024-38169, CVE-2024-38172, CVE-2024-38200', 8, 10, 80.0)
(380, 'CVE-2024-26199', 6, 9, 54.0)
(387, 'CVE-2023-33131', 8, 8, 64.0)
(399, 'CVE-2024-38119, CVE-2024-38230, CVE-2024-38236, CVE-2024-38240, CVE-2024-38241, CVE-2024-38242, CVE-2024-38249, CVE-2024-38250, CVE-2024-38252, CVE-2024-38253, CVE-2024-38254, CVE-2024-38256, CVE-2024-43467, CVE-2024-38014, CVE-2024-38046, CVE-2024-38217,', 7, 8, 56.0)
(404, 'CVE-2024-21404, CVE-2024-21386', 9, 7, 63.0)
(410, 'CVE-2023-36884', 10, 7, 70.0)
(415, 'CVE-2023-21823, CVE-2023-23376, CVE-2023-21805, CVE-2023-21702, CVE-2023-21701, CVE-2023-21700, CVE-2023-21699, CVE-2023-21697, CVE-2023-21695, CVE-2023-21694, CVE-2023-21693, CVE-2023-21692, CVE-2023-21691, CVE-2023-21690, CVE-2023-21689, CVE-2023-21688,', 7, 9, 63.0)
(430, 'CVE-2024-38173', 10, 9, 90.0)
(431, 'CVE-2023-35619, CVE-2023-35636', 10, 6, 60.0)
(432, 'CVE-2023-36009', 8, 7, 56.0)
(436, 'CVE-2024-29059', 7, 10, 70.0)
(439, 'CVE-2024-20690', 7, 10, 70.0)
(442, 'CVE-2023-36899, CVE-2023-36873', 9, 10, 90.0)
(443, 'CVE-2023-21722, CVE-2023-21808', 10, 10, 100.0)
(450, 'CVE-2024-4853', 10, 8, 80.0)
(464, 'CVE-2013-3900', 6, 10, 60.0)
(468, 'CVE-2024-13813', 10, 6, 60.0)
(469, 'CVE-2025-21262', 10, 8, 80.0)
(470, 'CVE-2024-8539, CVE-2024-38654, CVE-2024-9842, CVE-2024-9843, CVE-2024-29211, CVE-2024-37398, CVE-2024-7571', 9, 10, 90.0)
(472, 'CVE-2016-2183', 8, 8, 64.0)
(473, 'CVE-2017-15361', 10, 9, 90.0)
(477, 'nan', 9, 8, 72.0)
(479, 'nan', 10, 7, 70.0)
(481, 'CVE-2022-4135', 10, 7, 70.0)
(484, 'CVE-2022-34169, CVE-2022-21541, CVE-2022-21540, CVE-2022-21549', 8, 10, 80.0)
(495, 'CVE-2022-37963, CVE-2022-37962, CVE-2022-38010', 8, 10, 80.0)
(497, 'CVE-2022-41045, CVE-2022-41039, CVE-2022-41109, CVE-2022-41100, CVE-2022-41099, CVE-2022-41098, CVE-2022-41097, CVE-2022-41095, CVE-2022-41096, CVE-2022-41093, CVE-2022-41092, CVE-2022-41090, CVE-2022-41088, CVE-2022-41086, CVE-2022-41058, CVE-2022-41057,', 8, 10, 80.0)
(511, 'CVE-2022-22709, CVE-2022-21927, CVE-2022-21926, CVE-2022-21844', 9, 8, 72.0)
(518, 'CVE-2021-31984', 9, 9, 81.0)
(521, 'CVE-2021-28465', 9, 8, 72.0)
(522, 'CVE-2021-28466, CVE-2021-28464, CVE-2021-28468', 8, 9, 72.0)
(531, 'CVE-2020-14803', 9, 8, 72.0)
(539, 'CVE-2022-26832', 10, 10, 100.0)
(559, 'CVE-2025-1414', 10, 8, 80.0)
(561, 'CVE-2025-1016, CVE-2025-1019, CVE-2025-1013, CVE-2025-1010, CVE-2025-1017, CVE-2025-1020, CVE-2025-1011, CVE-2025-1018, CVE-2025-1012, CVE-2025-1014, CVE-2025-1009', 9, 8, 72.0)
(562, 'CVE-2025-0762', 8, 9, 72.0)
(572, 'CVE-2024-10467, CVE-2024-10461, CVE-2024-10468, CVE-2024-10466, CVE-2024-10463, CVE-2024-10459, CVE-2024-10465, CVE-2024-10460, CVE-2024-10462, CVE-2024-10458, CVE-2024-10464', 10, 6, 60.0)
(579, 'CVE-2023-41993, CVE-2024-21085, CVE-2024-21011, CVE-2024-21068, CVE-2024-21094, CVE-2024-21012, CVE-2024-21003, CVE-2024-21005, CVE-2024-21002, CVE-2024-21004', 8, 9, 72.0)
(586, 'CVE-2023-21835, CVE-2023-21830, CVE-2023-21843', 7, 9, 63.0)
(594, 'CVE-2025-21262', 9, 8, 72.0)
(597, 'CVE-2023-35080, CVE-2023-38543, CVE-2023-38043, CVE-2023-41718', 6, 10, 60.0)
(601, 'CVE-2023-40036, CVE-2023-40164, CVE-2023-40166, CVE-2023-40031', 8, 9, 72.0)
(615, 'CVE-2025-21307', 8, 9, 72.0)
(617, 'CVE-2024-43629, CVE-2024-43451, CVE-2024-43644, CVE-2024-43630, CVE-2024-43626, CVE-2024-49039, CVE-2024-38203, CVE-2024-43642, CVE-2024-43641, CVE-2024-43640, CVE-2024-43636, CVE-2024-43635, CVE-2024-43633, CVE-2024-43624, CVE-2024-43622, CVE-2024-43621,', 9, 6, 54.0)
(618, 'CVE-2024-43582, CVE-2024-43570, CVE-2024-43562, CVE-2024-43558, CVE-2024-43553, CVE-2024-43536, CVE-2024-43520, CVE-2024-43511, CVE-2024-37983, CVE-2024-43573, CVE-2024-43540, CVE-2024-43534, CVE-2024-43526, CVE-2024-43518, CVE-2024-43506, CVE-2024-43583,', 8, 8, 64.0)
(620, 'CVE-2024-38155, CVE-2024-38152, CVE-2024-38146, CVE-2024-38143, CVE-2024-38140, CVE-2024-38134, CVE-2024-38127, CVE-2024-38122, CVE-2024-38117, CVE-2024-38114, CVE-2024-38106, CVE-2024-38193, CVE-2024-38178, CVE-2024-38223, CVE-2024-38215, CVE-2024-38214,', 9, 6, 54.0)
(624, 'CVE-2025-0762', 10, 7, 70.0)
(627, 'CVE-2025-0411', 7, 10, 70.0)
(630, 'CVE-2024-49530, CVE-2024-49531, CVE-2024-49532, CVE-2024-49533, CVE-2024-49534, CVE-2024-49535', 8, 8, 64.0)
(635, 'CVE-2024-41869, CVE-2024-45112', 7, 10, 70.0)
(636, 'CVE-2024-39383, CVE-2024-39422, CVE-2024-39423, CVE-2024-39424, CVE-2024-39425, CVE-2024-39426, CVE-2024-41830, CVE-2024-41831, CVE-2024-41832, CVE-2024-41833, CVE-2024-41834, CVE-2024-41835, CVE-2024-39420, CVE-2024-45107', 9, 9, 81.0)
(637, 'CVE-2024-21147, CVE-2024-21145, CVE-2024-21140, CVE-2024-21144, CVE-2024-21131, CVE-2024-21138', 10, 7, 70.0)
(639, 'CVE-2023-38042', 6, 10, 60.0)
(643, 'CVE-2024-49026, CVE-2024-49027, CVE-2024-49028, CVE-2024-49029, CVE-2024-49030, CVE-2024-49031, CVE-2024-49032, CVE-2024-49033', 10, 7, 70.0)
(652, 'CVE-2024-30099, CVE-2024-30097, CVE-2024-30096, CVE-2024-35265, CVE-2024-30095, CVE-2024-30094, CVE-2024-30093, CVE-2024-30091, CVE-2024-30090, CVE-2024-30089, CVE-2024-30088, CVE-2024-30087, CVE-2024-30086, CVE-2024-30085, CVE-2024-30084, CVE-2024-30083,', 7, 8, 56.0)
(655, 'CVE-2023-38170', 10, 8, 80.0)
(657, 'CVE-2023-29340, CVE-2023-29341', 7, 9, 63.0)
(660, 'CVE-2022-30168', 9, 6, 54.0)
(662, 'CVE-2022-23300, CVE-2022-22007, CVE-2022-23301, CVE-2022-24451, CVE-2022-24452, CVE-2022-24453, CVE-2022-24457, CVE-2022-23295, CVE-2022-22006, CVE-2022-24501, CVE-2022-24456', 7, 9, 63.0)
(663, 'CVE-2022-22709, CVE-2022-21927, CVE-2022-21926, CVE-2022-21844', 7, 9, 63.0)
(675, 'CVE-2021-1643, CVE-2021-1644', 7, 10, 70.0)
(678, 'CVE-2025-23040', 7, 10, 70.0)
(680, 'CVE-2024-8539, CVE-2024-38654, CVE-2024-9842, CVE-2024-9843, CVE-2024-29211, CVE-2024-37398, CVE-2024-7571', 8, 9, 72.0)
(699, 'nan', 7, 8, 56.0)
(700, 'nan', 10, 6, 60.0)
(708, 'CVE-2023-29299, CVE-2023-29303, CVE-2023-29320, CVE-2023-38222, CVE-2023-38223, CVE-2023-38224, CVE-2023-38225, CVE-2023-38226, CVE-2023-38227, CVE-2023-38228, CVE-2023-38229, CVE-2023-38230, CVE-2023-38231, CVE-2023-38232, CVE-2023-38233, CVE-2023-38234,', 7, 9, 63.0)
(710, 'CVE-2024-21384, CVE-2024-20673, CVE-2024-21379, CVE-2024-21413', 8, 7, 56.0)
(714, 'CVE-2025-21217, CVE-2025-21246, CVE-2025-21334, CVE-2025-21374, CVE-2025-21343, CVE-2025-21340, CVE-2025-21312, CVE-2025-21300, CVE-2025-21292, CVE-2025-21276, CVE-2025-21189, CVE-2025-21261, CVE-2025-21278, CVE-2025-21229, CVE-2025-21228, CVE-2025-21331,', 9, 10, 90.0)
(730, 'CVE-2023-21729, CVE-2023-28302, CVE-2023-28298, CVE-2023-28297, CVE-2023-28293, CVE-2023-28253, CVE-2023-28275, CVE-2023-28276, CVE-2023-28252, CVE-2023-28274, CVE-2023-28273, CVE-2023-28249, CVE-2023-28272, CVE-2023-28271, CVE-2023-28247, CVE-2023-28248,', 10, 7, 70.0)
(731, 'CVE-2025-1006, CVE-2025-1426, CVE-2025-0999', 9, 8, 72.0)
(743, 'CVE-2024-12695, CVE-2024-12694, CVE-2024-12693, CVE-2024-12692', 9, 6, 54.0)
(745, 'CVE-2024-11477', 9, 9, 81.0)
(746, 'CVE-2024-11395', 7, 8, 56.0)
(750, 'CVE-2024-10826, CVE-2024-10827', 8, 8, 64.0)
(753, 'CVE-2024-9954, CVE-2024-9955, CVE-2024-9956, CVE-2024-9957, CVE-2024-9958, CVE-2024-9959, CVE-2024-9960, CVE-2024-9961, CVE-2024-9962, CVE-2024-9963, CVE-2024-9964, CVE-2024-9965, CVE-2024-9966', 9, 10, 90.0)
(765, 'CVE-2024-7532, CVE-2024-7533, CVE-2024-7550, CVE-2024-7534, CVE-2024-7535, CVE-2024-7536', 10, 8, 80.0)
(766, 'CVE-2024-6990, CVE-2024-7255, CVE-2024-7256', 7, 10, 70.0)
(774, 'CVE-2024-5274', 9, 10, 90.0)
(781, 'CVE-2024-4558, CVE-2024-4559', 9, 6, 54.0)
(794, 'CVE-2024-1284, CVE-2024-1283', 9, 8, 72.0)
(795, 'CVE-2024-1077, CVE-2024-1059, CVE-2024-1060, CVE-2024-21399', 9, 9, 81.0)
(800, 'CVE-2024-0208', 9, 10, 90.0)
(801, 'CVE-2024-0222, CVE-2024-0223, CVE-2024-0224, CVE-2024-0225', 7, 8, 56.0)
(805, 'CVE-2023-6351, CVE-2023-6350, CVE-2023-6348, CVE-2023-6347, CVE-2023-6346, CVE-2023-6345', 10, 9, 90.0)
(807, 'nan', 6, 10, 60.0)
(815, 'CVE-2023-5487, CVE-2023-5484, CVE-2023-5481, CVE-2023-5479, CVE-2023-5476, CVE-2023-5218, CVE-2023-5474, CVE-2023-5478, CVE-2023-5477, CVE-2023-5473, CVE-2023-5485, CVE-2023-5486, CVE-2023-5475, CVE-2023-5483', 8, 9, 72.0)
(819, 'CVE-2023-26369', 10, 6, 60.0)
(829, 'CVE-2023-3422, CVE-2023-3421, CVE-2023-3420', 9, 8, 72.0)
(832, 'CVE-2023-2722, CVE-2023-2724, CVE-2023-2723, CVE-2023-2721, CVE-2023-2725, CVE-2023-2726', 8, 7, 56.0)
(840, 'CVE-2023-0699, CVE-2023-0698, CVE-2023-0700, CVE-2023-0701, CVE-2023-0697, CVE-2023-0696, CVE-2023-21794, CVE-2023-0703, CVE-2023-0705, CVE-2023-0702, CVE-2023-0704', 9, 7, 63.0)
(841, 'CVE-2023-0705, CVE-2023-0703, CVE-2023-0702, CVE-2023-0701, CVE-2023-0704, CVE-2023-0697, CVE-2023-0700, CVE-2023-0698, CVE-2023-0699, CVE-2023-0696', 9, 7, 63.0)
(845, 'CVE-2022-21628, CVE-2022-21626, CVE-2022-21618, CVE-2022-39399, CVE-2022-21624, CVE-2022-21619', 9, 9, 81.0)
(848, 'CVE-2025-21395, CVE-2025-21366, CVE-2025-21365, CVE-2025-21338, CVE-2025-21364, CVE-2025-21363, CVE-2025-21362, CVE-2025-21402, CVE-2025-21356, CVE-2025-21354, CVE-2025-21186, CVE-2025-21346, CVE-2025-21345', 10, 7, 70.0)
(851, 'CVE-2024-43616, CVE-2024-43609, CVE-2024-43576, CVE-2024-43505, CVE-2024-43504', 9, 6, 54.0)
(852, 'CVE-2024-38016, CVE-2024-38226, CVE-2024-43465, CVE-2024-43463, CVE-2024-38250', 6, 10, 60.0)
(853, 'CVE-2024-38189, CVE-2024-38171, CVE-2024-38170, CVE-2024-38169, CVE-2024-38172, CVE-2024-38200', 8, 10, 80.0)
(856, 'CVE-2024-26199', 6, 9, 54.0)
(863, 'CVE-2023-33131', 8, 8, 64.0)
(875, 'CVE-2024-38119, CVE-2024-38230, CVE-2024-38236, CVE-2024-38240, CVE-2024-38241, CVE-2024-38242, CVE-2024-38249, CVE-2024-38250, CVE-2024-38252, CVE-2024-38253, CVE-2024-38254, CVE-2024-38256, CVE-2024-43467, CVE-2024-38014, CVE-2024-38046, CVE-2024-38217,', 7, 8, 56.0)
(880, 'CVE-2024-21404, CVE-2024-21386', 9, 7, 63.0)
(886, 'CVE-2023-36884', 10, 7, 70.0)
(891, 'CVE-2023-21823, CVE-2023-23376, CVE-2023-21805, CVE-2023-21702, CVE-2023-21701, CVE-2023-21700, CVE-2023-21699, CVE-2023-21697, CVE-2023-21695, CVE-2023-21694, CVE-2023-21693, CVE-2023-21692, CVE-2023-21691, CVE-2023-21690, CVE-2023-21689, CVE-2023-21688,', 7, 9, 63.0)
(906, 'CVE-2024-38173', 10, 9, 90.0)
(907, 'CVE-2023-35619, CVE-2023-35636', 10, 6, 60.0)
(908, 'CVE-2023-36009', 8, 7, 56.0)
(912, 'CVE-2024-29059', 7, 10, 70.0)
(915, 'CVE-2024-20690', 7, 10, 70.0)
(918, 'CVE-2023-36899, CVE-2023-36873', 9, 10, 90.0)
(919, 'CVE-2023-21722, CVE-2023-21808', 10, 10, 100.0)
(926, 'CVE-2024-4853', 10, 8, 80.0)
(940, 'CVE-2013-3900', 6, 10, 60.0)
(944, 'CVE-2024-13813', 10, 6, 60.0)
(945, 'CVE-2025-21262', 10, 8, 80.0)
(946, 'CVE-2024-8539, CVE-2024-38654, CVE-2024-9842, CVE-2024-9843, CVE-2024-29211, CVE-2024-37398, CVE-2024-7571', 9, 10, 90.0)
(948, 'CVE-2016-2183', 8, 8, 64.0)
(949, 'CVE-2017-15361', 10, 9, 90.0)
(953, 'nan', 9, 8, 72.0)
(955, 'nan', 10, 7, 70.0)